-- MySQL Script generated by MySQL Workbench
-- Fri Jun 28 12:23:52 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bd_yamaha_cotizations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bd_yamaha_cotizations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bd_yamaha_cotizations` DEFAULT CHARACTER SET utf8mb4 ;
USE `bd_yamaha_cotizations` ;


CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`tipo_users` (
  `id` int NOT NULL AUTO_INCREMENT,
  `nombre` varchar(200) DEFAULT NULL,
  `descripcion` varchar(500) DEFAULT NULL,
  `activo` tinyint DEFAULT NULL,
  `borrado` tinyint DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `indx_nombre` (`nombre` ASC) INVISIBLE,
  INDEX `indx_descripcion` (`descripcion` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) INVISIBLE
) ENGINE=InnoDB;

CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`users` (
  `id` BIGINT unsigned NOT NULL AUTO_INCREMENT,
  `name` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `email_verified_at` timestamp NULL DEFAULT NULL,
  `password` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL,
  `two_factor_secret` text COLLATE utf8mb4_unicode_ci,
  `two_factor_recovery_codes` text COLLATE utf8mb4_unicode_ci,
  `two_factor_confirmed_at` timestamp NULL DEFAULT NULL,
  `remember_token` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `current_team_id` bigint unsigned DEFAULT NULL,
  `profile_photo_path` varchar(2048) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `tipo_user_id` int DEFAULT NULL,
  `activo` tinyint DEFAULT NULL,
  `borrado` tinyint DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `users_email_unique` (`email`),
  INDEX `indx_name` (`name` ASC) INVISIBLE,
  INDEX `indx_password` (`password` ASC) INVISIBLE,
  INDEX `indx_remember_token` (`remember_token` ASC) INVISIBLE,
  INDEX `indx_current_team_id` (`current_team_id` ASC) INVISIBLE,
  INDEX `indx_tipo_user_id` (`tipo_user_id` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) INVISIBLE
) ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`tipo_documentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`tipo_documentos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NULL,
  `key` CHAR(10) NULL,
  `descripcion` VARCHAR(250) NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `indx_tipo` (`tipo` ASC) INVISIBLE,
  INDEX `indx_key` (`key` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`clientes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombres` VARCHAR(255) NULL,
  `apellidos` VARCHAR(255) NULL,
  `tipo_documento_id` INT NOT NULL,
  `documento` CHAR(25) NULL,
  `celular` VARCHAR(25) NULL,
  `correo` VARCHAR(250) NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_clientes_tipo_documentos_idx` (`tipo_documento_id` ASC) VISIBLE,
  INDEX `indx_documento` (`documento` ASC) INVISIBLE,
  INDEX `indx_celular` (`celular` ASC) VISIBLE,
  INDEX `indx_correo` (`correo` ASC) VISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE,
  CONSTRAINT `fk_clientes_tipo_documentos`
    FOREIGN KEY (`tipo_documento_id`)
    REFERENCES `bd_yamaha_cotizations`.`tipo_documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`personals`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`personals` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `user_id` BIGINT unsigned NOT NULL,
  `nombres` CHAR(150) NULL,
  `apellidos` CHAR(150) NULL,
  `celular` CHAR(25) NULL,
  `correo` CHAR(25) NULL,
  `tipo_documento_id` INT NOT NULL,
  `documentto` CHAR(25) NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_personals_tipo_documentos1_idx` (`tipo_documento_id` ASC) VISIBLE,
  INDEX `fk_personals_users1_idx` (`user_id` ASC) VISIBLE,
  INDEX `indx_nombres` (`nombres` ASC) INVISIBLE,
  INDEX `indx_apellidos` (`apellidos` ASC) INVISIBLE,
  INDEX `indx_celular` (`celular` ASC) INVISIBLE,
  INDEX `indx_correo` (`correo` ASC) INVISIBLE,
  INDEX `indx_documento` (`documentto` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE,
  CONSTRAINT `fk_personals_users1`
    FOREIGN KEY (`user_id`)
    REFERENCES `bd_yamaha_cotizations`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_personals_tipo_documentos1`
    FOREIGN KEY (`tipo_documento_id`)
    REFERENCES `bd_yamaha_cotizations`.`tipo_documentos` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`cotizacions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`cotizacions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `numero` CHAR(100) NULL,
  `modelo` CHAR(50) NULL,
  `year` INT NULL,
  `color` CHAR(100) NULL,
  `cliente_id` BIGINT NOT NULL,
  `pdf_url` TEXT NULL,
  `fecha` DATE NULL,
  `hora` TIME NULL,
  `fecha_fin` DATE NULL,
  `precio_usd` DOUBLE NULL,
  `descuento_usd` DOUBLE NULL,
  `precio_final_usd` DOUBLE NULL,
  `precio_final_pen` DOUBLE NULL,
  `personal_id` BIGINT NOT NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_cotizacions_clientes1_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `indx_numero` (`numero` ASC) VISIBLE,
  INDEX `indx_modelo` (`modelo` ASC) INVISIBLE,
  INDEX `indx_year` (`year` ASC) INVISIBLE,
  INDEX `indx_color` (`color` ASC) INVISIBLE,
  INDEX `fk_cotizacions_personals1_idx` (`personal_id` ASC) VISIBLE,
  INDEX `indx_fecha` (`fecha` ASC) INVISIBLE,
  INDEX `indx_hora` (`hora` ASC) INVISIBLE,
  INDEX `indx_fecha_fin` (`fecha_fin` ASC) VISIBLE,
  INDEX `indx_precio_usd` (`precio_usd` ASC) INVISIBLE,
  INDEX `indx_descuento_usd` (`descuento_usd` ASC) INVISIBLE,
  INDEX `indx_precio_final_usd` (`precio_final_usd` ASC) VISIBLE,
  INDEX `indx_precio_final_pen` (`precio_final_pen` ASC) VISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE,
  CONSTRAINT `fk_cotizacions_clientes1`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `bd_yamaha_cotizations`.`clientes` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_cotizacions_personals1`
    FOREIGN KEY (`personal_id`)
    REFERENCES `bd_yamaha_cotizations`.`personals` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`includes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`includes` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `nombre` CHAR(100) NULL,
  `urlimage` TEXT NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  `cotizacion_id` BIGINT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_includes_cotizacions1_idx` (`cotizacion_id` ASC) VISIBLE,
  INDEX `indx_nombre` (`nombre` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE,
  CONSTRAINT `fk_includes_cotizacions1`
    FOREIGN KEY (`cotizacion_id`)
    REFERENCES `bd_yamaha_cotizations`.`cotizacions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`categorias` (
  `id` BIGINT NOT NULL,
  `categoria` CHAR(100) NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `indx_categoria` (`categoria` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`subcategorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`subcategorias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `categoria_id` BIGINT NOT NULL,
  `subcategoria` CHAR(100) NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_subcategorias_categorias1_idx` (`categoria_id` ASC) VISIBLE,
  INDEX `indx_subcategoria` (`subcategoria` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE,
  CONSTRAINT `fk_subcategorias_categorias1`
    FOREIGN KEY (`categoria_id`)
    REFERENCES `bd_yamaha_cotizations`.`categorias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`maestro_modelos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`maestro_modelos` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `codigo` CHAR(50) NULL,
  `modelo` CHAR(100) NULL,
  `year` INT NULL,
  `categoria` CHAR(200) NULL,
  `subcategoria` CHAR(200) NULL,
  `color_fabrica` CHAR(150) NULL,
  `color_comercial` CHAR(150) NULL,
  `nombre_producto` CHAR(200) NULL,
  `linea_negocio` CHAR(10) NULL,
  `claim` CHAR(100) NULL,
  `descripcion` TEXT NULL,
  `color1` CHAR(100) NULL,
  `color2` CHAR(100) NULL,
  `color3` CHAR(100) NULL,
  `beneficio1` CHAR(200) NULL,
  `beneficio2` CHAR(200) NULL,
  `beneficio3` CHAR(200) NULL,
  `beneficio4` CHAR(200) NULL,
  `tipo_motor` CHAR(250) NULL,
  `cilindrada` CHAR(50) NULL,
  `potencia_max` CHAR(50) NULL,
  `torque_max` CHAR(50) NULL,
  `sistema_arrranque` CHAR(100) NULL,
  `sistema_transmision` CHAR(200) NULL,
  `suministro_combustible` CHAR(200) NULL,
  `capacidad_combustible` CHAR(50) NULL,
  `altura_asiento` CHAR(50) NULL,
  `peso_total` CHAR(50) NULL,
  `suspension_delantera` CHAR(100) NULL,
  `suspencion_trasera` CHAR(100) NULL,
  `freno_delantero` CHAR(100) NULL,
  `freno_trasero` CHAR(100) NULL,
  `neumatico_delantero` CHAR(100) NULL,
  `numatico_trasero` CHAR(100) NULL,
  `precio_usd` DOUBLE NULL,
  `descuento_usd` DOUBLE NULL,
  `precio_final_usd` DOUBLE NULL,
  `url_logo` TEXT NULL,
  `url_moto_principal` TEXT NULL,
  `url_color1` TEXT NULL,
  `url_color2` TEXT NULL,
  `url_color3` TEXT NULL,
  `url_beneficio1` TEXT NULL,
  `url_beneficio2` TEXT NULL,
  `url_beneficio3` TEXT NULL,
  `url_beneficio4` TEXT NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `indx_categoria` (`categoria` ASC) VISIBLE,
  INDEX `indx_subcategoria` (`subcategoria` ASC) VISIBLE,
  INDEX `indx_codigo` (`codigo` ASC) INVISIBLE,
  INDEX `indx_modelo` (`modelo` ASC) INVISIBLE,
  INDEX `indx_year` (`year` ASC) VISIBLE,
  INDEX `indx_color_fab` (`color_fabrica` ASC) INVISIBLE,
  INDEX `indx_color_com` (`color_comercial` ASC) INVISIBLE,
  INDEX `indx_nombre` (`nombre_producto` ASC) INVISIBLE,
  INDEX `indx_linea` (`linea_negocio` ASC) INVISIBLE,
  INDEX `indx_claim` (`claim` ASC) INVISIBLE,
  INDEX `indx_color1` (`color1` ASC) INVISIBLE,
  INDEX `indx_color2` (`color2` ASC) INVISIBLE,
  INDEX `indx_color3` (`color3` ASC) INVISIBLE,
  INDEX `indx_tipo_motor` (`tipo_motor` ASC) VISIBLE,
  INDEX `indx_cilindrada` (`cilindrada` ASC) INVISIBLE,
  INDEX `indx_potencia` (`potencia_max` ASC) INVISIBLE,
  INDEX `indx_torque` (`torque_max` ASC) INVISIBLE,
  INDEX `indx_arranque` (`sistema_arrranque` ASC) INVISIBLE,
  INDEX `indx_transmision` (`sistema_transmision` ASC) INVISIBLE,
  INDEX `indx_combustible` (`suministro_combustible` ASC) INVISIBLE,
  INDEX `indx_combustible_capacidad` (`capacidad_combustible` ASC) INVISIBLE,
  INDEX `indx_altura_asiento` (`altura_asiento` ASC) INVISIBLE,
  INDEX `indx_peso_total` (`peso_total` ASC) INVISIBLE,
  INDEX `indx_suspencion_delantera` (`suspension_delantera` ASC) INVISIBLE,
  INDEX `indx_suspension_trasera` (`suspencion_trasera` ASC) INVISIBLE,
  INDEX `indx_freno_delantero` (`freno_delantero` ASC) INVISIBLE,
  INDEX `indx_freno_trasero` (`freno_trasero` ASC) INVISIBLE,
  INDEX `indx_neumatico1` (`neumatico_delantero` ASC) INVISIBLE,
  INDEX `indx_neumatico2` (`numatico_trasero` ASC) INVISIBLE,
  INDEX `indx_precio_usd` (`precio_usd` ASC) INVISIBLE,
  INDEX `indx_descuento_usd` (`descuento_usd` ASC) INVISIBLE,
  INDEX `indx_precio_final_usd` (`precio_final_usd` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`configs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`configs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo_cambio` DOUBLE NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`garantias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`garantias` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `garantia` CHAR(200) NULL,
  `url_imagen` TEXT NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `indx_garantia` (`garantia` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`maestro_beneficios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`maestro_beneficios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `codigo` CHAR(50) NULL,
  `modelo` CHAR(50) NULL,
  `year` INT NULL,
  `color_fabrica` CHAR(100) NULL,
  `color_comercial` CHAR(100) NULL,
  `nombre_producto` CHAR(200) NULL,
  `linea_negocio` CHAR(10) NULL,
  `garantia_id` BIGINT NOT NULL,
  `beneficio1_id` BIGINT NULL,
  `beneficio1_status` TINYINT NULL,
  `beneficio2_id` BIGINT NULL,
  `beneficio2_status` TINYINT NULL,
  `beneficio3_id` BIGINT NULL,
  `beneficio3_status` TINYINT NULL,
  `beneficio4_id` BIGINT NULL,
  `beneficio4_status` TINYINT NULL,
  `beneficio5_id` BIGINT NULL,
  `beneficio5_status` TINYINT NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_maestro_beneficios_garantias1_idx` (`garantia_id` ASC) VISIBLE,
  INDEX `indx_codigo` (`codigo` ASC) INVISIBLE,
  INDEX `indx_modelo` (`modelo` ASC) VISIBLE,
  INDEX `indx_year` (`year` ASC) INVISIBLE,
  INDEX `indx_color1` (`color_fabrica` ASC) VISIBLE,
  INDEX `indx_color2` (`color_comercial` ASC) INVISIBLE,
  INDEX `indx_nombre` (`nombre_producto` ASC) INVISIBLE,
  INDEX `indx_linea` (`linea_negocio` ASC) INVISIBLE,
  INDEX `indx_beneficio1` (`beneficio1_id` ASC) INVISIBLE,
  INDEX `indx_beneficio1s` (`beneficio1_status` ASC) VISIBLE,
  INDEX `indx_beneficio2` (`beneficio2_id` ASC) INVISIBLE,
  INDEX `indx_beneficio2s` (`beneficio2_status` ASC) VISIBLE,
  INDEX `indx_beneficio3` (`beneficio3_id` ASC) INVISIBLE,
  INDEX `indx_beneficio3s` (`beneficio3_status` ASC) INVISIBLE,
  INDEX `indx_beneficio4` (`beneficio4_id` ASC) INVISIBLE,
  INDEX `indx_beneficio4s` (`beneficio4_status` ASC) INVISIBLE,
  INDEX `indx_beneficio5` (`beneficio5_id` ASC) VISIBLE,
  INDEX `indx_beneficio5s` (`beneficio5_status` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE,
  CONSTRAINT `fk_maestro_beneficios_garantias1`
    FOREIGN KEY (`garantia_id`)
    REFERENCES `bd_yamaha_cotizations`.`garantias` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`beneficios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`beneficios` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `beneficio` CHAR(100) NULL,
  `url_beneficio` TEXT NULL,
  `type` TINYINT NULL COMMENT '1-> normal\n2->opcional',
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `indx_beneficio` (`beneficio` ASC) INVISIBLE,
  INDEX `indx_type` (`type` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bd_yamaha_cotizations`.`data_cotizacions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bd_yamaha_cotizations`.`data_cotizacions` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `codigo` CHAR(50) NULL,
  `modelo` CHAR(100) NULL,
  `year` INT NULL,
  `color_fabrica` CHAR(150) NULL,
  `color_comercial` CHAR(150) NULL,
  `nombre_producto` CHAR(200) NULL,
  `linea_negocio` CHAR(10) NULL,
  `claim` CHAR(100) NULL,
  `descripcion` TEXT NULL,
  `color1` CHAR(100) NULL,
  `color2` CHAR(100) NULL,
  `color3` CHAR(100) NULL,
  `beneficio1` CHAR(200) NULL,
  `beneficio2` CHAR(200) NULL,
  `beneficio3` CHAR(200) NULL,
  `beneficio4` CHAR(200) NULL,
  `tipo_motor` CHAR(250) NULL,
  `cilindrada` CHAR(50) NULL,
  `potencia_max` CHAR(50) NULL,
  `torque_max` CHAR(50) NULL,
  `sistema_arrranque` CHAR(100) NULL,
  `sistema_transmision` CHAR(200) NULL,
  `suministro_combustible` CHAR(200) NULL,
  `capacidad_combustible` CHAR(50) NULL,
  `altura_asiento` CHAR(50) NULL,
  `peso_total` CHAR(50) NULL,
  `suspension_delantera` CHAR(100) NULL,
  `suspencion_trasera` CHAR(100) NULL,
  `freno_delantero` CHAR(100) NULL,
  `freno_trasero` CHAR(100) NULL,
  `neumatico_delantero` CHAR(100) NULL,
  `numatico_trasero` CHAR(100) NULL,
  `precio_usd` DOUBLE NULL,
  `categoria` CHAR(200) NULL,
  `subcategoria` CHAR(200) NULL,
  `cotizacion_id` BIGINT NOT NULL,
  `maestro_modelo_id` BIGINT NULL,
  `url_logo` TEXT NULL,
  `url_moto_principal` TEXT NULL,
  `url_color1` TEXT NULL,
  `url_color2` TEXT NULL,
  `url_color3` TEXT NULL,
  `url_beneficio1` TEXT NULL,
  `url_beneficio2` TEXT NULL,
  `url_beneficio3` TEXT NULL,
  `url_beneficio4` TEXT NULL,
  `activo` TINYINT NULL,
  `borrado` TINYINT NULL,
  `created_at` TIMESTAMP NULL,
  `updated_at` TIMESTAMP NULL,
  PRIMARY KEY (`id`),
  INDEX `indx_codigo` (`codigo` ASC) INVISIBLE,
  INDEX `indx_modelo` (`modelo` ASC) INVISIBLE,
  INDEX `indx_year` (`year` ASC) VISIBLE,
  INDEX `indx_color_fab` (`color_fabrica` ASC) INVISIBLE,
  INDEX `indx_color_com` (`color_comercial` ASC) INVISIBLE,
  INDEX `indx_nombre` (`nombre_producto` ASC) INVISIBLE,
  INDEX `indx_linea` (`linea_negocio` ASC) INVISIBLE,
  INDEX `indx_claim` (`claim` ASC) INVISIBLE,
  INDEX `indx_color1` (`color1` ASC) INVISIBLE,
  INDEX `indx_color2` (`color2` ASC) INVISIBLE,
  INDEX `indx_color3` (`color3` ASC) INVISIBLE,
  INDEX `indx_tipo_motor` (`tipo_motor` ASC) VISIBLE,
  INDEX `indx_cilindrada` (`cilindrada` ASC) INVISIBLE,
  INDEX `indx_potencia` (`potencia_max` ASC) INVISIBLE,
  INDEX `indx_torque` (`torque_max` ASC) INVISIBLE,
  INDEX `indx_arranque` (`sistema_arrranque` ASC) INVISIBLE,
  INDEX `indx_transmision` (`sistema_transmision` ASC) INVISIBLE,
  INDEX `indx_combustible` (`suministro_combustible` ASC) INVISIBLE,
  INDEX `indx_combustible_capacidad` (`capacidad_combustible` ASC) INVISIBLE,
  INDEX `indx_altura_asiento` (`altura_asiento` ASC) INVISIBLE,
  INDEX `indx_peso_total` (`peso_total` ASC) INVISIBLE,
  INDEX `indx_suspencion_delantera` (`suspension_delantera` ASC) INVISIBLE,
  INDEX `indx_suspension_trasera` (`suspencion_trasera` ASC) INVISIBLE,
  INDEX `indx_freno_delantero` (`freno_delantero` ASC) INVISIBLE,
  INDEX `indx_freno_trasero` (`freno_trasero` ASC) INVISIBLE,
  INDEX `indx_neumatico1` (`neumatico_delantero` ASC) INVISIBLE,
  INDEX `indx_neumatico2` (`numatico_trasero` ASC) INVISIBLE,
  INDEX `indx_precio_usd` (`precio_usd` ASC) INVISIBLE,
  INDEX `indx_activo` (`activo` ASC) INVISIBLE,
  INDEX `indx_borrado` (`borrado` ASC) VISIBLE,
  INDEX `indx_categoria` (`categoria` ASC) INVISIBLE,
  INDEX `indx_subcategoria` (`subcategoria` ASC) VISIBLE,
  INDEX `fk_data_cotizacions_cotizacions1_idx` (`cotizacion_id` ASC) VISIBLE,
  CONSTRAINT `fk_data_cotizacions_cotizacions1`
    FOREIGN KEY (`cotizacion_id`)
    REFERENCES `bd_yamaha_cotizations`.`cotizacions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
